name: Code Quality

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: salt-lite-integration
          target: integration
          secret-files: GITHUB_TOKEN=./github-token.txt
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=${{ runner.temp }}/salt-lite-integration.tar
      - uses: actions/upload-artifact@v4
        with:
          name: salt-lite-integration
          path: ${{ runner.temp }}/salt-lite-integration.tar

  run-check:
    strategy:
      matrix:
        tool: [ lint, phpcs, phpunit, phpstan, rector-dry-run]
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: salt-lite-integration
          path: ${{ runner.temp }}
      - run: docker load --input ${{ runner.temp }}/salt-lite-integration.tar
      - run: docker run --rm --user 1000:1000 salt-lite-integration composer run-script ${{ matrix.tool }}